config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  resources :posts
  resources :users
  resources :comments

  get '/users/:id' => 'users#show'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :commenter, :class_name => "User"
end
# <a href="/posts/new">Create a post</a>

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :author, :class_name => "User"
  has_many :comments

  validates :title, :body, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.username = username.downcase }

  has_many :posts, :foreign_key => :author_id
  has_many :comments, :foreign_key => :commenter_id

  has_secure_password

  validates :username, :presence => true, :uniqueness => true
  validates :password, :presence => true, :length => { minimum: 3 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def session_user
    if session[:user_id]
      @user ||= User.find(session[:user_id])
    end
  end

  def session_user_id
    session_user.id.to_i
  end

  helper_method :session_user
  helper_method :session_user_id
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = session_user.posts.new(post_params)
    if @post.save
      redirect_to "/"
    else
      render "posts/new"
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update_attributes(post_params)
    if @post.valid?
      redirect_to "/"
    else
      render "posts/edit"
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to '/'
  end

  def post_params
    params.require(:post).permit(:title, :body, :id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
    render layout:false
  end

  def create
    @user = User.find_by(username: params[:user][:username])
    if @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to @user
    else
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to "/"
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render layout:false
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to '/'
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HackerNews</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <h1><a href="/">Hacker News</a></h1>
  <p>
    <a href="#posts">new</a>
    <a href="#">comments</a>
    <a href="#">popular</a>
    <p id="login">
    <% if session[:user_id] %>
      <%= link_to("Logout", logout_path, method: :delete)  %>
    <% else %>
    <%= link_to("Login", login_path)  %>
    <%= link_to("Register", new_user_path)  %>
    </p>
    <% end %>
  </p>
</header>
<%= yield %>

</body>
</html>

app/views/posts/_post.html.erb
<article id="<%= @post.id %>">
    <a href='/posts/<%= @post.id %>/vote' class="fa fa-sort-desc vote-button"></a>
    <h2><a href='/posts/<%= @post.id %>'><%= @post.title %></a></h2>
    <p>
    <span class='username'><a href='/users/:id'><%= @post.author.username %></a></span>
    <span class='timestamp'><%= @post.created_at %></span>
    <span class='comment-count'><%= @post.comments.count %></span>
    </p>
</article>
<div class="delete-button"><%= link_to "delete", post_path, method: :delete %></div>

app/views/posts/edit.html.erb
<%= form_tag(post_path, method: "put") do %>
  <%= label_tag(:title, "Title:") %>
  <%= text_field_tag("post[title]", @post.title) %>
  <%= label_tag(:body, "Body:") %>
  <%= text_area_tag("post[body]", @post.body, size: "44x26") %>
  <%= submit_tag("Update Post") %>
<% end %>

app/views/posts/index.html.erb
<div class="post-container">
  <% @posts.each do |post| %>
      <article id="<%= post.id %>">
        <a href='/posts/<%= post.id %>/vote' class="fa fa-sort-desc vote-button"></a>
        <h2> <%= link_to post.title, posts_path(post) %> </h2>
        <p>
        <span class='username'><a href='<%=user_path(post.author)%>'><%= post.author.username %></a></span>
        <span class='comment-count'><%= post.comments.count %></span>
        <% if session_user && session_user_id == post.author.id %>
        <span class="edit"><%= link_to "edit", edit_post_path(post), method: :get %></span>
        <span class="delete"><%= link_to "delete", post_path(post), method: :delete %></span>
        <% end %>
        </p>
    </article>
   <% end %>

    <div id="new-post-button>"><%= link_to "Create Post", new_post_path %></div>
</div>

app/views/posts/new.html.erb
<%= form_tag("/posts", method: "post") do %>
  <%= label_tag(:title, "Title:") %>
  <%= text_field_tag("post[title]") %>
  <%= label_tag(:body, "Body:") %>
  <%= text_area_tag("post[body]", "", size: "44x26") %>
  <%= submit_tag("Create Post") %>
<% end %>

app/views/posts/show.html.erb
<%= render "post" %>
<p><%= @post.body %></p>

app/views/users/new.html.erb
<%= form_tag("/users", method: "post") do %>
  <%= label_tag(:username, "Username:") %>
  <%=text_field_tag("user[username]") %>
  <%= label_tag(:password, "Password") %>
  <%=password_field_tag("user[password]") %>
  <%= submit_tag("Register") %>
<% end %>

app/views/users/show.html.erb
<div id="user_info">
  <h4>user: <%= @user.username %></h4>
  <h4>created: <%= @user.created_at %></h4>
  <a href="/users/<%= @user.id %>/comments">comments</a>
</div>